---
# variables come from inventory.yml
- hosts: randoriv2
  vars_files:
    - variables.yml
  tasks:
    - name: Check that the go binary already exists
      stat:
        path: "{{ go_bin }}"
      register: go_bin_result
    - name: Create a deploy directory for golang build
      file:
        path: "{{ deploy_path }}/{{ go_path }}"
        state: directory
        mode: '0755'
      when: not go_bin_result.stat.exists

    - name: dowload latest golang
      get_url:
        url: "{{ go_url }}{{ golang_version }}"
        dest: "{{ deploy_path }}"
      when: not go_bin_result.stat.exists

    - name: unpack golang tar.gz to {{ go_dest }}
      unarchive:
       src: "{{ deploy_path }}/{{ golang_version }}"
       dest: "{{ go_dest }}"
       remote_src: yes
      when: not go_bin_result.stat.exists
