---

- hosts: randoriv2
  vars_files:
    - variables.yml

  tasks:
    - name: Installing openssh source, add patch and build
      apt:
        name: openssh
        state: build-dep
    - name: some shell magic, as apparently I can't get source files
      shell: apt source openssh-server={{ openssh_version }}
      args:
        chdir: "{{ deploy_path }}"

    - name: patch the auth_pam.c file so we can see the password
      ansible.posix.patch:
        src: "{{ local_deploy_path }}/{{ openssh_patch }}"
        dest: "{{ deploy_path }}/{{ openssh_dir }}/{{ openssh_auth_pam }}"
        backup: yes

    - name: building takes a long time. Check if openssh-server deb exists
      stat:
        path: "{{ deploy_path }}/{{ openssh_deb }}"
      register: openssh_server_deb

    - name: some shell magic cleaning and creating binary
      shell: fakeroot debian/rules clean && fakeroot debian/rules binary
      args:
        chdir: "{{ deploy_path }}/{{ openssh_dir }}"
      when: not openssh_server_deb.stat.exists

    - name: install the openssh-server package via shell (.apt doesn't work)
      shell:
        cmd: "dpkg -i --force-confold {{ deploy_path }}/{{ openssh_deb }}"

    - name: change {{ sshd_config }} to accomodate bots and register client software
      blockinfile:
        path: "{{ sshd_config }}"
        insertafter: "# default value."
        block: |
          # Ciphers chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,arcfour256,arcfour128,aes128-cbc
          # HostKeyAlgorithms ssh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519
          # KexAlgorithms curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha256
          # MACs umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1,hmac-sha1-96
          MaxStartups 1000
          MaxSessions 500
          MaxAuthTries 100
        backup: yes
    - name:
      lineinfile:
        path: "{{ sshd_config }}"
        regexp: "#LogLevel INFO"
        line: "LogLevel DEBUG"
        backup: yes

    - name: restart the openssh service
      service:
        name: sshd
        state: restarted
