---

- hosts: randoriv2
  remote_user: root
  gather_facts: true
  vars:
    golang_version: "go1.15.5.linux-amd64.tar.gz"
    deploy_path: "/tmp/deploy"
    go_path: "gopath"
    go_bin: "/usr/local/go/bin"
    go_ssh_common_go: "src/golang.org/x/crypto/ssh/common.go"
    copy_files:
      - deploy/randorifan.go
      - deploy/randorisink.go
      - deploy/torissh.go
      - deploy/toritelnet.go
  tasks:
    - name: check for zmq install
      stat:
        path: "{{ deploy_path }}/{{ go_path }}/src/github.com/pebbe/zmq4"
      register: zmq4

    - name: install go zmq4 module
      shell: go get github.com/pebbe/zmq4
      environment:
        PATH: "{{ ansible_env.PATH }}:{{ go_bin }}"
        GOPATH: "{{ deploy_path }}/{{ go_path }}"
      when: not zmq4.stat.isdir

    - name: check for go ssh install
      stat:
        path: "{{ deploy_path }}/{{ go_path }}/src/golang.org/x/crypto/ssh"
      register: ssh

    - name: install go ssh module
      shell: go get golang.org/x/crypto/ssh
      environment:
        PATH: "{{ ansible_env.PATH }}:{{ go_bin }}"
        GOPATH: "{{ deploy_path }}/{{ go_path }}"
      when: not ssh.stat.isdir

        #  "$PATH" is a literal string in 'environment:', so use ansible_env.PATH
        # - name: test path
        #   shell: echo "$PATH $GOPATH" >> /tmp/test
        #   environment:
        #     PATH: "{{ ansible_env.PATH }}:{{ go_bin }}"
        #     GOPATH: "{{ deploy_path }}/{{ go_path }}"


    - name: install go ssh module
      shell: go get golang.org/x/crypto/ssh
      environment:
        PATH: "{{ ansible_env.PATH }}:{{ go_bin }}"
        GOPATH: "{{ deploy_path }}/{{ go_path }}"

    - name: degrade the go ssh module so it can handle bad ciphers
      replace:
        # hardcoded regex
        path: "{{ deploy_path }}/{{ go_path }}/{{ go_ssh_common_go }}"
        regexp: ' "arcfour128", "arcfour"'
        replace: ' "arcfour128", "aes128-cbc", "arcfour"'
        backup: yes

    - name: copy over the randori and tori go files
      copy:
        src: "{{ item }}"
        dest: "{{ deploy_path }}/{{ go_path }}"
      with_items: "{{ copy_files }}"

    # XXX code is old, and replaced with pebbe/zmq4
    # Needs to be redesigned
    # TODO
    - name: build randorifan.go
      shell: "go build {{ deploy_path }}/{{ go_path }}/randorifan.go"
      environment:
        PATH: "{{ ansible_env.PATH }}:{{ go_bin }}"
        GOPATH: "{{ deploy_path }}/{{ go_path }}"

