---

- hosts: randoriv2
  vars_files:
    - variables.yml
  tasks:
    - name: check for zmq install
      stat:
        path: "{{ deploy_path }}/{{ go_path }}/src/{{ go_zmq4_url }}"
      register: zmq4

    - name: install go zmq4 module
      shell: go get {{ go_zmq4_url }}
      environment:
        PATH: "{{ ansible_env.PATH }}:{{ go_bin }}"
        GOPATH: "{{ deploy_path }}/{{ go_path }}"
      when: not zmq4.stat.exists

    - name: check for go ssh install
      stat:
        path: "{{ deploy_path }}/{{ go_path }}/src/{{ go_ssh_url }}"
      register: ssh

    - name: install go ssh module
      shell: go get {{ go_ssh_url }}
      environment:
        PATH: "{{ ansible_env.PATH }}:{{ go_bin }}"
        GOPATH: "{{ deploy_path }}/{{ go_path }}"
      when: not ssh.stat.exists

        #  "$PATH" is a literal string in 'environment:', so use ansible_env.PATH
        # - name: test path
        #   shell: echo "$PATH $GOPATH" >> /tmp/test
        #   environment:
        #     PATH: "{{ ansible_env.PATH }}:{{ go_bin }}"
        #     GOPATH: "{{ deploy_path }}/{{ go_path }}"

    - name: degrade the go ssh module so it can handle bad ciphers
      replace:
        # hardcoded regex/replace
        path: "{{ deploy_path }}/{{ go_path }}/{{ go_ssh_common_go }}"
        regexp: ' "arcfour128", "arcfour"'
        replace: ' "arcfour128", "aes128-cbc", "arcfour"'
        backup: yes

    - name: touch {{ randori_log }}
      copy:
        content: ""
        dest: "{{ randori_log }}"
        force: no
        group: adm
        owner: syslog
        mode: 0640

    # XXX The randori code is old, and I replaced gozmq with pebbe/zmq4
    # It currently compiles, but needs to be debugged
    # TODO run these as services.

    - name: copy randorifan source
      copy:
        src: "{{ local_deploy_path }}/{{ randorifan_go }}"
        dest: "{{ deploy_path }}/{{ go_path }}"
      register: randorifan

    - name: build {{ randorifan_go }}
      shell: "go build {{ deploy_path }}/{{ go_path }}/{{ randorifan_go }}"
      environment:
        PATH: "{{ ansible_env.PATH }}:{{ go_bin }}"
        GOPATH: "{{ deploy_path }}/{{ go_path }}"
      when: randorifan.changed

    - name: copy randorisink source
      copy:
        src: "{{ local_deploy_path }}/{{ randorisink_go }}"
        dest: "{{ deploy_path }}/{{ go_path }}"
      register: randorisink

    - name: build {{ randorisink_go }}
      shell: "go build {{ deploy_path }}/{{ go_path }}/{{ randorisink_go }}"
      environment:
        PATH: "{{ ansible_env.PATH }}:{{ go_bin }}"
        GOPATH: "{{ deploy_path }}/{{ go_path }}"
      when: randorisink.changed

    - name: copy torissh source
      copy:
        src: "{{ local_deploy_path }}/{{ torissh_go }}"
        dest: "{{ deploy_path }}/{{ go_path }}"
      register: torissh

    - name: build {{ torissh_go }}
      shell: "go build {{ deploy_path }}/{{ go_path }}/{{ torissh_go }}"
      environment:
        PATH: "{{ ansible_env.PATH }}:{{ go_bin }}"
        GOPATH: "{{ deploy_path }}/{{ go_path }}"
      when: torissh.changed
