---

- hosts: randoriv2
  vars_files:
    - secrets.yml
  remote_user: root
  gather_facts: false
  tasks:
    - name: Set passwordAuthentication yes
      lineinfile:
        path: /etc/ssh/sshd_config
        regex: ^#PasswordAuthentication(.*[yes|no])
        line: PasswordAuthentication yes
    - name: restart ssh
      service:
        name: ssh
        state: reloaded
    - user: name=root password={{ root_password | string | password_hash('sha512') }}
