---

- hosts: randoriv2
  vars_files:
    - secrets.yml
    - variables.yml
  tasks:
    - name: Set PasswordAuthentication yes in sshd_config
      lineinfile:
        path: /etc/ssh/sshd_config
        # works because comments in sshd_config start with: '# ', defaults with: '#'
        regex: ^#PasswordAuthentication(.*[yes|no])
        line: PasswordAuthentication yes
    - name: reload ssh
      service:
        name: ssh
        state: reloaded
    - user: name=root password={{ root_password | string | password_hash('sha512') }}
